#!/bin/bash

# Set the path to your project
project_path="../src"

# Check if the migration name is provided as an argument
if [ $# -eq 0 ]; then
    echo "Usage: $0 <migration_name>"
    exit 1
fi

# Set the migration name from the command-line argument
migration_name="$1"

# Navigate to the project directory
cd "$project_path"

# Run Entity Framework migrations
dotnet ef migrations add $migration_name --project Chirp.Infrastructure --startup-project Chirp.Web

# Run Entity Framework database update
dotnet ef database update --project Chirp.Infrastructure --startup-project Chirp.Web

# Inform the user
echo "Migration done"